version: "3.7"

services:
  web:
    container_name: nodeapp
    image: vimalesh198/nodedockerapp:2.0
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - 3000:3000
    networks:
      - node-app-networks
    volumes:
      - ./logs:/var/www/logs
    depends_on:
      - db

  db:
    container_name: "mongodb"
    image: mongo
    networks:
      - node-app-networks

networks:
  node-app-networks:
    driver: bridge
